### ISSUE TITLE
loginAsPassword が使用できない。

### ISSUE THREAD

**Issue by mattyatea** [shiosyakeyakini-info/misskey_dart#54]
loginAsPasswordを使用しようとするとエラーが出て使えません。
https://github.com/shiosyakeyakini-info/misskey_dart/blob/91d4c3f631c872678a87d85e463b84866ac9b7be/lib/src/server.dart#L44
が token になっているのが原因だと思われます。
(signin で帰って来るresponseには、 userId と i があり、 i にtokenが入っている)

**Comment by shiosyakeyakini-info** [comment]
これloginAsPasswordを残してるほうが誤りな気がしてきた
Cookieの情報とかを返してないのと、signupをサードパーティが呼ぶのは避けるべきだから

キーが間違ってるように見えるのはたぶんこれもともとめいどるふぃん用に書いたのをそのまま残してしまってるだけだった気がする
